//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Amigo
    {
        public int id { get; set; }
        public int idPelotero { get; set; }
        public int idAmigo { get; set; }
    
        public virtual Pelotero Pelotero { get; set; }
        public virtual Pelotero Pelotero1 { get; set; }
    }
}
