//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cancha
    {
        public Cancha()
        {
            this.CentroDeportivoCancha = new HashSet<CentroDeportivoCancha>();
            this.Reserva = new HashSet<Reserva>();
        }
    
        public int id { get; set; }
        public int largo { get; set; }
        public int ancho { get; set; }
        public int precio { get; set; }
        public bool activo { get; set; }
        public string tipoCampo { get; set; }
    
        public virtual ICollection<CentroDeportivoCancha> CentroDeportivoCancha { get; set; }
        public virtual ICollection<Reserva> Reserva { get; set; }
    }
}
