//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class CentroDeportivo
    {
        public CentroDeportivo()
        {
            this.Campo = new HashSet<Campo>();
        }
    
        public int id { get; set; }
        public string direccion { get; set; }
        public string telefono { get; set; }
        public string celular { get; set; }
        public int idDistrito { get; set; }
        public string nroCanchas { get; set; }
        public bool balon { get; set; }
        public bool camisetas { get; set; }
        public int idEmpresa { get; set; }
        public string nombre { get; set; }
        public string foto { get; set; }
        public double latitud { get; set; }
        public double longitud { get; set; }
        public bool activo { get; set; }
    
        public virtual ICollection<Campo> Campo { get; set; }
        public virtual Distrito Distrito { get; set; }
        public virtual Empresa Empresa { get; set; }
    }
}
