//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Distrito
    {
        public Distrito()
        {
            this.CentroDeportivo = new HashSet<CentroDeportivo>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public int idProvincia { get; set; }
        public bool activo { get; set; }
    
        public virtual ICollection<CentroDeportivo> CentroDeportivo { get; set; }
        public virtual Provincia Provincia { get; set; }
    }
}
