//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reserva
    {
        public Reserva()
        {
            this.DetalleInvitados = new HashSet<DetalleInvitados>();
        }
    
        public int id { get; set; }
        public System.DateTime fechaHora { get; set; }
        public int idUsuario { get; set; }
        public int idCancha { get; set; }
        public bool activo { get; set; }
        public Nullable<System.TimeSpan> horaInicio { get; set; }
        public Nullable<System.TimeSpan> horaFin { get; set; }
    
        public virtual Cancha Cancha { get; set; }
        public virtual ICollection<DetalleInvitados> DetalleInvitados { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
